name: Publish compile and publish binary

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-submit:
    name: Compile for ${{ matrix.os }}-${{ matrix.arch }} using node ${{ matrix.node-version }} and upload on the bin branch
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x]
        arch: [x64, arm64]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: set node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        npm install node-gyp node-pre-gyp -g
    - name: compile and package
      run: node-pre-gyp configure build package
    - name : copy results
      run : |
        mv ./build/stage/raw/bin/builds ./
        rm -rf ./build
        ls -al 
    - name: Switch to bin branch
      run: git checkout bin
    - name: add, commit and push
      run: |
        ls -al 
        git add ./builds
        git config --global user.email "github.action@nothing.com"
        git config --global user.name "Github Action"
        git commit -m "add binary"
        git push origin bin
