name: Publish compile and publish binary

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-save:
    name: Compile for ${{ matrix.os }}-${{ matrix.arch }} using node ${{ matrix.node-version }} and upload on the bin branch
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x, 16.x, 17.x, 18.x, 19.x]
        arch: [x64]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: set node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: |
        npm install node-gyp node-pre-gyp -g
    - name: compile and package
      run: node-pre-gyp configure build package
    - name: Upload data
      uses: actions/upload-artifact@v3
      with:
        name: Builds
        path: ./build/stage/raw/bin/
        retention-days: 1

  load-and-commit:
    needs: build-and-save
    runs-on: ubuntu-latest
    steps:
    - name: Switch to bin branch
      uses: actions/checkout@v3
      with:
        ref: bin
    - name: Download data
      uses: actions/download-artifact@v3
      with:
        name: Builds
    - name: add, commit and push   
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: 'add binary'

